import HeaderNav from '@/components/head/HeaderNav'
import './globals.css'
import Providers from './Providers'
import Navbar from '@/components/nav/Navbar'

export const metadata = {
  title: 'IMBd Web application',
  description: 'Generated by IMBd',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className='min-h-screen flex flex-col'>
            <HeaderNav />
            <Navbar />

            <div className='flex-grow'>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  )
}
