import HeaderNav from '@/components/head/HeaderNav'
import './globals.css'
import Providers from './Providers'
import Navbar from '@/components/nav/Navbar'

export const metadata = {
  title: 'IMBd Web application',
  description: 'Generated by IMBd',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <HeaderNav />
          <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  )
}
