import HeaderNav from '@/components/head/HeaderNav'
import './globals.css'

export const metadata = {
  title: 'IMBd Web application',
  description: 'Generated by IMBd',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderNav />
        {children}
      </body>
    </html>
  )
}
